### ISSUE TITLE
Filter: "Session -> Time on Page" Not Available for Page Exit Event

### ISSUE THREAD

**Issue by chsWeb** [ak--47/mpEZTrack#19]
**SUMMARY:**
In the demo video ([@ 3:30](https://youtu.be/rYvVXST2loY?t=207)) a filter for "**Session -> Time on Page**" is applied to Page Exit. 

**PROBLEM:**
The filter is not available.

**STEPS TO REPRODUCE:**
1. Create new insight report
2. Elect Page Exit event
3. Apply filter to Page Exit
4. Search for Session -> time on page
5. No results. Only SESSION + # pages is available

**EXPECTED RESULT:**
**Session -> Time on Page** should appear as a filter option, however it does not.

**Comment by ak--47** [comment]
closing due to lack of response.
