### ISSUE TITLE
Page lost focus & page regained focus appear in data despite window: false

### ISSUE THREAD

**Issue by chsWeb** [ak--47/mpEZTrack#21]
I am using Google Tag Manager to implement EZ Track on a WordPress + Divi site, as follows:

```
<script src="https://mpeztrack.com/v1.0.0/eztrack.min.js" type="text/javascript"></script>
<script>
mpEZTrack.init("project_token", {window: false});
</script>
```

In my data, I still see page focus events occurring - see screen grab attached.

![image](https://github.com/ak--47/mpEZTrack/assets/873222/b85361d7-0b37-4adf-b308-7ab3f710cfa8)

Do I have something wrong, or is this a bug?

**Comment by ak--47** [comment]
@chsWeb nothing is wrong. there's very few of those events, and they appear to be 0 towards the end of your chart. 

the 1 or 2 of these fired when you first installed the snippet and perhaps you added the window : false bit on a subsequent save. every GTM save goes through a headless browser on google's side so it doesn't let you push busted code.

events not fired in 30 days will disappear from the dropdowns. if they really bother you, you can hide events in lexicon:
https://docs.mixpanel.com/docs/data-governance/lexicon
